export const synthesis: Record<string, string> = {
  meaning:
    "Across these five traditions, meaning is located in strikingly different places — in relationship with a creator, in ethical practice and community, or in the individual's own reasoned choices. Christianity, Islam, and Judaism each tie meaning to a relationship with God, though they differ in whether that relationship centers on love, submission, or covenant and practice. Buddhism stands apart by questioning whether a fixed answer to 'why are we here' is even the right kind of question to ask. Stoicism relocates meaning entirely inward, into virtue and reason, independent of any external relationship at all.",
  suffering:
    "Every tradition here treats suffering as a serious problem worth a real answer, but the proposed relationship to it varies. Buddhism offers the most systematic account — suffering has an identified cause and a corresponding path out of it. Christianity and Islam both frame suffering as meaningful within a larger relationship with God, whether as shared experience or as purifying test. Judaism is notable for holding multiple, sometimes unresolved views in tension rather than settling on one. Stoicism differs from all four by locating suffering not in events themselves but in our judgments about them.",
  death:
    "The traditions split most clearly here between those affirming a personal afterlife and those that don't. Christianity and Islam both describe bodily resurrection and divine judgment, differing mainly in specific theological structure. Judaism holds this question more loosely, without a single settled doctrine. Buddhism reframes death through rebirth and the absence of a fixed self, while Stoicism treats death as a natural, impersonal transformation with no promise of continued individual existence at all.",
  consciousness:
    "Views on the self range from something eternal and God-given to something that may not exist as a fixed thing at all. Christianity and Islam both affirm a soul distinct from the body, though Islam's concept of the nafs treats the self as more dynamically contested. Judaism tends toward a more integrated, embodied view of personhood. Buddhism's doctrine of non-self is the most radical departure here, treating the intuitive sense of 'I' as constructed rather than fundamental. Stoicism identifies the self specifically with rational judgment, distinct from body or circumstance.",
  morality:
    "Moral foundations here split between divine command, consequence-oriented reasoning, and reason-based virtue. Christianity, Islam, and Judaism all root ethics substantially in divine instruction, though the degree of legal specificity varies considerably — Judaism and Islam both developed extensive legal traditions, while Christianity leans more on exemplar and principle. Buddhism's ethics are oriented significantly around reducing suffering. Stoicism stands apart as the one tradition here that grounds morality in reason and virtue without appeal to divine command at all.",
  "free-will":
    "This is a question where several traditions hold an internal tension rather than a clean resolution. Christianity, Islam, and Judaism each affirm human free will while also affirming a form of divine sovereignty or foreknowledge, and each has generated centuries of internal debate over how those fit together. Buddhism offers a middle position — actions are conditioned by prior causes, yet still carry moral weight. Stoicism distinguishes fate, which governs external events, from freedom, which is our judgment about them — a version of this same idea in a fully non-theistic form.",
  identity:
    "Identity is variously located in relationship to God, in community and practice, or in an inner rational core untouched by circumstance. Christianity and Islam both connect identity closely to one's standing before God. Judaism treats identity as unusually multidimensional, resisting reduction to belief alone. Buddhism again offers the most distinct position, treating identity as a continuously changing process rather than a fixed essence. Stoicism, meanwhile, argues that true identity is exactly what remains once external roles and circumstances are stripped away.",
};